name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: arch-linux
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.8.0
      env:
        # ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build/web
